# Site settings
title: Curtis Ullerich
email: web@curtis.in
description: > # this means to ignore newlines until "baseurl:"
  Things I've done and made.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username:  curtisullerich

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/


